apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: jupyter-operator
  namespace: default
rules:
- apiGroups:
  - jupyter.sapyens.org
  resources:
  - notebooks
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - services
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - "*"
