// Code generated by kubernetes/code-generator. DO NOT EDIT.

/*
Copyright 2017 Lucas Servén

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	jupyter_v1 "github.com/squat/jupyter-operator/pkg/apis/jupyter/v1"
	versioned "github.com/squat/jupyter-operator/pkg/clientset/versioned"
	internalinterfaces "github.com/squat/jupyter-operator/pkg/informers/externalversions/internalinterfaces"
	v1 "github.com/squat/jupyter-operator/pkg/listers/jupyter/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// NotebookInformer provides access to a shared informer and lister for
// Notebooks.
type NotebookInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.NotebookLister
}

type notebookInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewNotebookInformer constructs a new informer for Notebook type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNotebookInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.JupyterV1().Notebooks(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.JupyterV1().Notebooks(namespace).Watch(options)
			},
		},
		&jupyter_v1.Notebook{},
		resyncPeriod,
		indexers,
	)
}

func defaultNotebookInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewNotebookInformer(client, meta_v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *notebookInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&jupyter_v1.Notebook{}, defaultNotebookInformer)
}

func (f *notebookInformer) Lister() v1.NotebookLister {
	return v1.NewNotebookLister(f.Informer().GetIndexer())
}
