apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: jupyter-operator
  namespace: jupyter
rules:
- apiGroups:
  - jupyter.squat.ai
  resources:
  - notebooks
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - "*"
