// Code generated by kubernetes/code-generator. DO NOT EDIT.

/*
Copyright 2018 Lucas Servén Marín

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	jupyterv1 "github.com/squat/jupyter-operator/pkg/apis/jupyter/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNotebooks implements NotebookInterface
type FakeNotebooks struct {
	Fake *FakeJupyterV1
	ns   string
}

var notebooksResource = schema.GroupVersionResource{Group: "jupyter", Version: "v1", Resource: "notebooks"}

var notebooksKind = schema.GroupVersionKind{Group: "jupyter", Version: "v1", Kind: "Notebook"}

// Get takes name of the notebook, and returns the corresponding notebook object, and an error if there is any.
func (c *FakeNotebooks) Get(name string, options v1.GetOptions) (result *jupyterv1.Notebook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(notebooksResource, c.ns, name), &jupyterv1.Notebook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jupyterv1.Notebook), err
}

// List takes label and field selectors, and returns the list of Notebooks that match those selectors.
func (c *FakeNotebooks) List(opts v1.ListOptions) (result *jupyterv1.NotebookList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(notebooksResource, notebooksKind, c.ns, opts), &jupyterv1.NotebookList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &jupyterv1.NotebookList{ListMeta: obj.(*jupyterv1.NotebookList).ListMeta}
	for _, item := range obj.(*jupyterv1.NotebookList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested notebooks.
func (c *FakeNotebooks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(notebooksResource, c.ns, opts))

}

// Create takes the representation of a notebook and creates it.  Returns the server's representation of the notebook, and an error, if there is any.
func (c *FakeNotebooks) Create(notebook *jupyterv1.Notebook) (result *jupyterv1.Notebook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(notebooksResource, c.ns, notebook), &jupyterv1.Notebook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jupyterv1.Notebook), err
}

// Update takes the representation of a notebook and updates it. Returns the server's representation of the notebook, and an error, if there is any.
func (c *FakeNotebooks) Update(notebook *jupyterv1.Notebook) (result *jupyterv1.Notebook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(notebooksResource, c.ns, notebook), &jupyterv1.Notebook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jupyterv1.Notebook), err
}

// Delete takes name of the notebook and deletes it. Returns an error if one occurs.
func (c *FakeNotebooks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(notebooksResource, c.ns, name), &jupyterv1.Notebook{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNotebooks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(notebooksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &jupyterv1.NotebookList{})
	return err
}

// Patch applies the patch and returns the patched notebook.
func (c *FakeNotebooks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *jupyterv1.Notebook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(notebooksResource, c.ns, name, data, subresources...), &jupyterv1.Notebook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jupyterv1.Notebook), err
}
